# pywal -> ~/.cache/wal/colors-hyprland.conf  (bordes del wallpaper)
general {{
    col.active_border = rgb({color4.strip}) rgb({color6.strip}) 45deg
    col.inactive_border = rgb({color8.strip})
}}

decoration {{
    shadow {{
        color = rgba({background.strip}ee)
    }}
}}

misc {{
    background_color = rgb({background.strip})
}}
